// ====================================================================================================== //
// This module is the iact data spad.
// Iact data spad stores the data vector and count vector generated by CSC decoder.
//
// For convolution layer, iact data spad stores the weight data.
// For depthwise-convolution and fully connected layer, iact data spad stores the iact data.
//
// Modified version:
// - Remove BRAM IP
// - Use LUT / reg-array style storage
// - Remove sequential clear logic
// - Do NOT reset whole mem[] on reset, to improve LUTRAM inference
// - Keep synchronous read behavior (1-cycle registered output)
// ====================================================================================================== //

module Iact_Data_Spad
#(
    parameter integer IACT_DATA_W      = 13,   // 8b data + 5b count
    parameter integer IACT_DATA_ADDR_W = 8
)
(
    input                               clock,
    input                               reset,
    // data signals
    output                              data_in_ready,
    input   [IACT_DATA_W-1:0]           data_in,
    input                               data_in_valid,
    output  reg [IACT_DATA_W-1:0]       data_out,
    // control signals
    input                               write_en,
    output                              write_fin,
    input   [IACT_DATA_ADDR_W-1:0]      read_idx
);

// ================================================ //
//                    Parameters                    //
// ================================================ //
localparam integer SPAD_DEPTH = 200;

// ================================================ //
//                    Registers                     //
// ================================================ //
(* ram_style = "distributed" *)
reg [IACT_DATA_W-1:0] mem [0:SPAD_DEPTH-1];

reg [IACT_DATA_ADDR_W-1:0] spad_write_addr;

// ================================================ //
//                 Basic handshake                  //
// ================================================ //
// No sequential clear busy anymore.
// During reset, do not accept input.
assign data_in_ready = ~reset;

wire data_in_shake;
assign data_in_shake = data_in_ready & data_in_valid & write_en;

// write finished when sentinel 0 is written
assign write_fin = (data_in == {IACT_DATA_W{1'b0}}) & data_in_shake;

// ================================================ //
//              Memory / pointer control            //
// ================================================ //
always @(posedge clock) begin
    if (reset) begin
        spad_write_addr <= {IACT_DATA_ADDR_W{1'b0}};
        data_out        <= {IACT_DATA_W{1'b0}};
    end
    else begin
        // write path
        if (data_in_shake) begin
            mem[spad_write_addr] <= data_in;

            if (write_fin) begin
                spad_write_addr <= {IACT_DATA_ADDR_W{1'b0}};
            end
            else begin
                spad_write_addr <= spad_write_addr + {{(IACT_DATA_ADDR_W-1){1'b0}}, 1'b1};
            end
        end

        // synchronous read path: keep same 1-cycle style as old BRAM-based version
        data_out <= mem[read_idx];
    end
end

endmodule