// ====================================================================================================== //
// This module is the iact address spad.
// Iact address spad stores the segment boundary vector generated by CSC decoder.
// For each segment index rd_seg_idx:
//   seg_begin = address_spad[rd_seg_idx]
//   seg_end   = address_spad[rd_seg_idx + 1]
// ====================================================================================================== //

module Iact_Address_Spad
#(
    parameter integer IACT_SEG_IDX_W  = 5,
    parameter integer IACT_DATA_PTR_W = 8
)
(
    input                               clock,
    input                               reset,
    // data in signals
    output                              data_in_ready,
    input                               data_in_valid,
    input   [IACT_DATA_PTR_W-1:0]       data_in,
    // data out signals
    input   [IACT_SEG_IDX_W-1:0]        rd_seg_idx,
    output  [IACT_DATA_PTR_W-1:0]       seg_begin,
    output  [IACT_DATA_PTR_W-1:0]       seg_end,
    // control signals
    input                               write_en,
    output                              write_fin
);

// ================================================ //
//                    Parameters                    //
// ================================================ //
localparam integer SPAD_DEPTH = 12;
localparam [IACT_DATA_PTR_W-1:0] IACT_ADDR_SENTINEL = {IACT_DATA_PTR_W{1'b1}};
localparam integer WRITE_ADDR_W = $clog2(SPAD_DEPTH);

// ================================================ //
//                    Registers                     //
// ================================================ //
reg [IACT_DATA_PTR_W-1:0] iact_address_spad [0:SPAD_DEPTH-1];
reg [WRITE_ADDR_W-1:0]    data_write_addr;

reg [IACT_DATA_PTR_W-1:0] seg_begin_reg;
reg [IACT_DATA_PTR_W-1:0] seg_end_reg;

// ================================================ //
//                      Wires                       //
// ================================================ //
wire data_in_shake;
wire [IACT_SEG_IDX_W:0] rd_seg_idx_ext;
wire [IACT_SEG_IDX_W:0] rd_seg_idx_p1;

// ================================================ //
//                 Basic handshake                  //
// ================================================ //
assign data_in_ready = 1'b1;
assign data_in_shake = data_in_ready & data_in_valid & write_en;
assign write_fin     = data_in_shake & (data_in == IACT_ADDR_SENTINEL);

assign rd_seg_idx_ext = {1'b0, rd_seg_idx};
assign rd_seg_idx_p1  = rd_seg_idx_ext + 1'b1;

assign seg_begin = seg_begin_reg;
assign seg_end   = seg_end_reg;

// ================================================ //
//                  Sequential write                //
// ================================================ //
integer i;
always @(posedge clock) begin
    if (reset) begin
        for (i = 0; i < SPAD_DEPTH; i = i + 1) begin
            iact_address_spad[i] <= IACT_ADDR_SENTINEL;
        end
    end
    else if (data_in_shake) begin
        iact_address_spad[data_write_addr] <= data_in;
    end
end

// write address pointer
always @(posedge clock) begin
    if (reset) begin
        data_write_addr <= 'd0;
    end
    else if (data_in_shake) begin
        if (write_fin) begin
            data_write_addr <= 'd0;
        end
        else begin
            if (data_write_addr < SPAD_DEPTH-1)
                data_write_addr <= data_write_addr + 'd1;
            else
                data_write_addr <= 'd0;
        end
    end
end

// ================================================ //
//                Combinational read                //
// ================================================ //
always @(*) begin
    // default
    seg_begin_reg = IACT_ADDR_SENTINEL;
    seg_end_reg   = IACT_ADDR_SENTINEL;

    if (rd_seg_idx_ext < SPAD_DEPTH)
        seg_begin_reg = iact_address_spad[rd_seg_idx];

    if (rd_seg_idx_p1 < SPAD_DEPTH)
        seg_end_reg = iact_address_spad[rd_seg_idx_p1[IACT_SEG_IDX_W-1:0]];
end

endmodule