// ====================================================================================================== //
// This module is the weight data spad.
// Weight data spad stores packed data/count words generated by CSC decoder.
//
// One 24b word contains 2 lanes:
//   lane0 = {lane0_value[7:0], lane0_count[3:0]}  -> bits [11:0]
//   lane1 = {lane1_value[7:0], lane1_count[3:0]}  -> bits [23:12]
//
// Modified version:
// - Remove BRAM IP
// - Use LUT / reg-array style storage
// - Remove sequential clear logic
// - Do NOT reset whole mem[] on reset, to improve LUTRAM inference
// - Keep synchronous read behavior (1-cycle registered output)
// ====================================================================================================== //

module Weight_Data_Spad
#(
    parameter integer WEIGHT_PACKED_W   = 24,   // two 12b data packed in one 24b word
    parameter integer WEIGHT_WORD_PTR_W = 7,
    parameter integer WEIGHT_COUNT_W    = 4,
    parameter integer WEIGHT_VALUE_W    = 8
)
(
    input                               clock,
    input                               reset,
    // data in signals
    output                              data_in_ready,
    input                               data_in_valid,
    input   [WEIGHT_PACKED_W-1:0]       data_in,
    // data out signals
    output  [WEIGHT_VALUE_W-1:0]        lane0_value,
    output  [WEIGHT_COUNT_W-1:0]        lane0_count,
    output  [WEIGHT_VALUE_W-1:0]        lane1_value,
    output  [WEIGHT_COUNT_W-1:0]        lane1_count,
    // control signals
    input                               write_en,
    output                              write_fin,
    input                               read_en,
    input   [WEIGHT_WORD_PTR_W-1:0]     read_word_idx,
    output                              lane0_valid,
    output                              lane1_valid
);

// ================================================ //
//                    Parameters                    //
// ================================================ //
localparam integer SPAD_DEPTH = 100;

// ================================================ //
//                    Registers                     //
// ================================================ //
(* ram_style = "distributed" *)
reg [WEIGHT_PACKED_W-1:0] mem [0:SPAD_DEPTH-1];

reg [WEIGHT_WORD_PTR_W-1:0] spad_write_addr;
reg                         rd_fire_d;
reg [WEIGHT_PACKED_W-1:0]   mem_data_out;

// packed lane split
wire [WEIGHT_VALUE_W+WEIGHT_COUNT_W-1:0] lane0_packed;
wire [WEIGHT_VALUE_W+WEIGHT_COUNT_W-1:0] lane1_packed;

wire data_in_shake;
wire rd_fire;

// ================================================ //
//                 Basic handshake                  //
// ================================================ //
assign data_in_ready = ~reset;
assign data_in_shake = data_in_ready & data_in_valid & write_en;

// write finished when sentinel 0 word is written
assign write_fin = (data_in == {WEIGHT_PACKED_W{1'b0}}) & data_in_shake;

// Keep old arbitration style:
// if write happens this cycle, normal read is not served this cycle
assign rd_fire = read_en & ~data_in_shake;

// ================================================ //
//              Memory / pointer control            //
// ================================================ //
always @(posedge clock) begin
    if (reset) begin
        spad_write_addr <= {WEIGHT_WORD_PTR_W{1'b0}};
        rd_fire_d       <= 1'b0;
        mem_data_out    <= {WEIGHT_PACKED_W{1'b0}};
    end
    else begin
        // write path
        if (data_in_shake) begin
            mem[spad_write_addr] <= data_in;

            if (write_fin) begin
                spad_write_addr <= {WEIGHT_WORD_PTR_W{1'b0}};
            end
            else begin
                spad_write_addr <= spad_write_addr + {{(WEIGHT_WORD_PTR_W-1){1'b0}}, 1'b1};
            end
        end

        // synchronous read path: one-cycle registered output
        // when a write is happening, suppress normal read output just like old BRAM wrapper
        if (rd_fire) begin
            mem_data_out <= mem[read_word_idx];
        end
        else begin
            mem_data_out <= {WEIGHT_PACKED_W{1'b0}};
        end

        // read-valid delayed by 1 cycle
        rd_fire_d <= rd_fire;
    end
end

// ================================================ //
//                   Output unpack                  //
// ================================================ //
// Assumed packing:
//   lane0 = data_out[11:0]  = {value[11:4], count[3:0]}
//   lane1 = data_out[23:12] = {value[11:4], count[3:0]}
assign lane0_packed = mem_data_out[WEIGHT_VALUE_W+WEIGHT_COUNT_W-1:0];
assign lane1_packed = mem_data_out[2*(WEIGHT_VALUE_W+WEIGHT_COUNT_W)-1 : (WEIGHT_VALUE_W+WEIGHT_COUNT_W)];

assign lane0_count = lane0_packed[WEIGHT_COUNT_W-1:0];
assign lane0_value = lane0_packed[WEIGHT_VALUE_W+WEIGHT_COUNT_W-1 : WEIGHT_COUNT_W];

assign lane1_count = lane1_packed[WEIGHT_COUNT_W-1:0];
assign lane1_value = lane1_packed[WEIGHT_VALUE_W+WEIGHT_COUNT_W-1 : WEIGHT_COUNT_W];

// valid in cycle after read request
// lane is invalid if packed lane value is zero
assign lane0_valid = rd_fire_d & (lane0_value != {WEIGHT_VALUE_W{1'b0}});
assign lane1_valid = rd_fire_d & (lane1_value != {WEIGHT_VALUE_W{1'b0}});

endmodule