# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Eyeriss v2 Accelerator/PE/PE.srcs/sources_1/ip/IP_Psum_DATA_Spad_BRAM/IP_Psum_DATA_Spad_BRAM.xci
# IP: The module: 'IP_Psum_DATA_Spad_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Eyeriss v2 Accelerator/PE/PE.gen/sources_1/ip/IP_Psum_DATA_Spad_BRAM/IP_Psum_DATA_Spad_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_Psum_DATA_Spad_BRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Eyeriss v2 Accelerator/PE/PE.srcs/sources_1/ip/IP_Psum_DATA_Spad_BRAM/IP_Psum_DATA_Spad_BRAM.xci
# IP: The module: 'IP_Psum_DATA_Spad_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Eyeriss v2 Accelerator/PE/PE.gen/sources_1/ip/IP_Psum_DATA_Spad_BRAM/IP_Psum_DATA_Spad_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_Psum_DATA_Spad_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
