# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/IP_Weight_DATA_Spad_BRAM/IP_Weight_DATA_Spad_BRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_Weight_DATA_Spad_BRAM || ORIG_REF_NAME==IP_Weight_DATA_Spad_BRAM} -quiet] -quiet
