`timescale 1ns/1ps

// ============================================================================
// Module      : Router_Cluster
// Author      : Do Quoc Khanh
// Description : Source/path fabric for local IACT, Weight, and PSUM streams.
//               Contains 3 IACT physical-lane routers, 3 Weight row routers,
//               and 4 PSUM column routers.
//               It does not generate schedules or PE delivery masks; those
//               decisions remain in the Dataflow Controller/local fabric path.
// ============================================================================
module Router_Cluster (
    input  wire [5:0]   iact_data_in_sel_in,
    input  wire [8:0]   iact_route_mask_in,
    input  wire [2:0]   weight_data_in_sel_in,
    input  wire [2:0]   weight_route_horizontal_in,
    input  wire [3:0]   psum_data_in_sel_in,
    input  wire [3:0]   psum_route_to_pe_in,

    input  wire [5:0]   local_iact_addr_valid_in,
    output wire [5:0]   local_iact_addr_ready_out,
    input  wire [29:0]  local_iact_addr_in,
    input  wire [5:0]   local_iact_data_valid_in,
    output wire [5:0]   local_iact_data_ready_out,
    input  wire [71:0]  local_iact_data_in,
    input  wire [5:0]   north_iact_addr_valid_in,
    output wire [5:0]   north_iact_addr_ready_out,
    input  wire [29:0]  north_iact_addr_in,
    input  wire [5:0]   north_iact_data_valid_in,
    output wire [5:0]   north_iact_data_ready_out,
    input  wire [71:0]  north_iact_data_in,
    input  wire [5:0]   south_iact_addr_valid_in,
    output wire [5:0]   south_iact_addr_ready_out,
    input  wire [29:0]  south_iact_addr_in,
    input  wire [5:0]   south_iact_data_valid_in,
    output wire [5:0]   south_iact_data_ready_out,
    input  wire [71:0]  south_iact_data_in,
    input  wire [5:0]   horizontal_iact_addr_valid_in,
    output wire [5:0]   horizontal_iact_addr_ready_out,
    input  wire [29:0]  horizontal_iact_addr_in,
    input  wire [5:0]   horizontal_iact_data_valid_in,
    output wire [5:0]   horizontal_iact_data_ready_out,
    input  wire [71:0]  horizontal_iact_data_in,

    output wire [5:0]   pe_iact_addr_valid_out,
    input  wire [5:0]   pe_iact_addr_ready_in,
    output wire [29:0]  pe_iact_addr_out,
    output wire [5:0]   pe_iact_data_valid_out,
    input  wire [5:0]   pe_iact_data_ready_in,
    output wire [71:0]  pe_iact_data_out,
    output wire [5:0]   north_iact_addr_valid_out,
    input  wire [5:0]   north_iact_addr_ready_in,
    output wire [29:0]  north_iact_addr_out,
    output wire [5:0]   north_iact_data_valid_out,
    input  wire [5:0]   north_iact_data_ready_in,
    output wire [71:0]  north_iact_data_out,
    output wire [5:0]   south_iact_addr_valid_out,
    input  wire [5:0]   south_iact_addr_ready_in,
    output wire [29:0]  south_iact_addr_out,
    output wire [5:0]   south_iact_data_valid_out,
    input  wire [5:0]   south_iact_data_ready_in,
    output wire [71:0]  south_iact_data_out,
    output wire [5:0]   horizontal_iact_addr_valid_out,
    input  wire [5:0]   horizontal_iact_addr_ready_in,
    output wire [29:0]  horizontal_iact_addr_out,
    output wire [5:0]   horizontal_iact_data_valid_out,
    input  wire [5:0]   horizontal_iact_data_ready_in,
    output wire [71:0]  horizontal_iact_data_out,

    input  wire [2:0]   local_weight_addr_valid_in,
    output wire [2:0]   local_weight_addr_ready_out,
    input  wire [20:0]  local_weight_addr_in,
    input  wire [2:0]   local_weight_data_valid_in,
    output wire [2:0]   local_weight_data_ready_out,
    input  wire [71:0]  local_weight_data_in,
    input  wire [2:0]   horizontal_weight_addr_valid_in,
    output wire [2:0]   horizontal_weight_addr_ready_out,
    input  wire [20:0]  horizontal_weight_addr_in,
    input  wire [2:0]   horizontal_weight_data_valid_in,
    output wire [2:0]   horizontal_weight_data_ready_out,
    input  wire [71:0]  horizontal_weight_data_in,
    output wire [2:0]   pe_weight_addr_valid_out,
    input  wire [2:0]   pe_weight_addr_ready_in,
    output wire [20:0]  pe_weight_addr_out,
    output wire [2:0]   pe_weight_data_valid_out,
    input  wire [2:0]   pe_weight_data_ready_in,
    output wire [71:0]  pe_weight_data_out,
    output wire [2:0]   horizontal_weight_addr_valid_out,
    input  wire [2:0]   horizontal_weight_addr_ready_in,
    output wire [20:0]  horizontal_weight_addr_out,
    output wire [2:0]   horizontal_weight_data_valid_out,
    input  wire [2:0]   horizontal_weight_data_ready_in,
    output wire [71:0]  horizontal_weight_data_out,

    input  wire [3:0]   pe_psum_return_valid_in,
    output wire [3:0]   pe_psum_return_ready_out,
    input  wire [167:0] pe_psum_return_data_in,
    output wire [3:0]   local_psum_return_valid_out,
    input  wire [3:0]   local_psum_return_ready_in,
    output wire [167:0] local_psum_return_data_out,
    input  wire [3:0]   local_psum_forward_valid_in,
    output wire [3:0]   local_psum_forward_ready_out,
    input  wire [167:0] local_psum_forward_data_in,
    input  wire [3:0]   north_psum_forward_valid_in,
    output wire [3:0]   north_psum_forward_ready_out,
    input  wire [167:0] north_psum_forward_data_in,
    output wire [3:0]   pe_psum_forward_valid_out,
    input  wire [3:0]   pe_psum_forward_ready_in,
    output wire [167:0] pe_psum_forward_data_out,
    output wire [3:0]   south_psum_forward_valid_out,
    input  wire [3:0]   south_psum_forward_ready_in,
    output wire [167:0] south_psum_forward_data_out
);

    genvar lane;
    generate
        for (lane = 0; lane < 3; lane = lane + 1) begin : g_iact_router
            Iact_Router u_iact_router (
                .data_in_sel_in(iact_data_in_sel_in[lane*2 +: 2]),
                .route_mask_in(iact_route_mask_in[lane*3 +: 3]),
                .local_addr_valid_in(local_iact_addr_valid_in[lane*2 +: 2]),
                .local_addr_ready_out(local_iact_addr_ready_out[lane*2 +: 2]),
                .local_addr_in(local_iact_addr_in[lane*10 +: 10]),
                .local_data_valid_in(local_iact_data_valid_in[lane*2 +: 2]),
                .local_data_ready_out(local_iact_data_ready_out[lane*2 +: 2]),
                .local_data_in(local_iact_data_in[lane*24 +: 24]),
                .north_addr_valid_in(north_iact_addr_valid_in[lane*2 +: 2]),
                .north_addr_ready_out(north_iact_addr_ready_out[lane*2 +: 2]),
                .north_addr_in(north_iact_addr_in[lane*10 +: 10]),
                .north_data_valid_in(north_iact_data_valid_in[lane*2 +: 2]),
                .north_data_ready_out(north_iact_data_ready_out[lane*2 +: 2]),
                .north_data_in(north_iact_data_in[lane*24 +: 24]),
                .south_addr_valid_in(south_iact_addr_valid_in[lane*2 +: 2]),
                .south_addr_ready_out(south_iact_addr_ready_out[lane*2 +: 2]),
                .south_addr_in(south_iact_addr_in[lane*10 +: 10]),
                .south_data_valid_in(south_iact_data_valid_in[lane*2 +: 2]),
                .south_data_ready_out(south_iact_data_ready_out[lane*2 +: 2]),
                .south_data_in(south_iact_data_in[lane*24 +: 24]),
                .horizontal_addr_valid_in(horizontal_iact_addr_valid_in[lane*2 +: 2]),
                .horizontal_addr_ready_out(horizontal_iact_addr_ready_out[lane*2 +: 2]),
                .horizontal_addr_in(horizontal_iact_addr_in[lane*10 +: 10]),
                .horizontal_data_valid_in(horizontal_iact_data_valid_in[lane*2 +: 2]),
                .horizontal_data_ready_out(horizontal_iact_data_ready_out[lane*2 +: 2]),
                .horizontal_data_in(horizontal_iact_data_in[lane*24 +: 24]),
                .pe_addr_valid_out(pe_iact_addr_valid_out[lane*2 +: 2]),
                .pe_addr_ready_in(pe_iact_addr_ready_in[lane*2 +: 2]),
                .pe_addr_out(pe_iact_addr_out[lane*10 +: 10]),
                .pe_data_valid_out(pe_iact_data_valid_out[lane*2 +: 2]),
                .pe_data_ready_in(pe_iact_data_ready_in[lane*2 +: 2]),
                .pe_data_out(pe_iact_data_out[lane*24 +: 24]),
                .north_addr_valid_out(north_iact_addr_valid_out[lane*2 +: 2]),
                .north_addr_ready_in(north_iact_addr_ready_in[lane*2 +: 2]),
                .north_addr_out(north_iact_addr_out[lane*10 +: 10]),
                .north_data_valid_out(north_iact_data_valid_out[lane*2 +: 2]),
                .north_data_ready_in(north_iact_data_ready_in[lane*2 +: 2]),
                .north_data_out(north_iact_data_out[lane*24 +: 24]),
                .south_addr_valid_out(south_iact_addr_valid_out[lane*2 +: 2]),
                .south_addr_ready_in(south_iact_addr_ready_in[lane*2 +: 2]),
                .south_addr_out(south_iact_addr_out[lane*10 +: 10]),
                .south_data_valid_out(south_iact_data_valid_out[lane*2 +: 2]),
                .south_data_ready_in(south_iact_data_ready_in[lane*2 +: 2]),
                .south_data_out(south_iact_data_out[lane*24 +: 24]),
                .horizontal_addr_valid_out(horizontal_iact_addr_valid_out[lane*2 +: 2]),
                .horizontal_addr_ready_in(horizontal_iact_addr_ready_in[lane*2 +: 2]),
                .horizontal_addr_out(horizontal_iact_addr_out[lane*10 +: 10]),
                .horizontal_data_valid_out(horizontal_iact_data_valid_out[lane*2 +: 2]),
                .horizontal_data_ready_in(horizontal_iact_data_ready_in[lane*2 +: 2]),
                .horizontal_data_out(horizontal_iact_data_out[lane*24 +: 24])
            );
        end

        for (lane = 0; lane < 3; lane = lane + 1) begin : g_weight_router
            Weight_Router u_weight_router (
                .data_in_sel_in(weight_data_in_sel_in[lane]),
                .route_horizontal_in(weight_route_horizontal_in[lane]),
                .local_addr_valid_in(local_weight_addr_valid_in[lane]),
                .local_addr_ready_out(local_weight_addr_ready_out[lane]),
                .local_addr_in(local_weight_addr_in[lane*7 +: 7]),
                .local_data_valid_in(local_weight_data_valid_in[lane]),
                .local_data_ready_out(local_weight_data_ready_out[lane]),
                .local_data_in(local_weight_data_in[lane*24 +: 24]),
                .horizontal_addr_valid_in(horizontal_weight_addr_valid_in[lane]),
                .horizontal_addr_ready_out(horizontal_weight_addr_ready_out[lane]),
                .horizontal_addr_in(horizontal_weight_addr_in[lane*7 +: 7]),
                .horizontal_data_valid_in(horizontal_weight_data_valid_in[lane]),
                .horizontal_data_ready_out(horizontal_weight_data_ready_out[lane]),
                .horizontal_data_in(horizontal_weight_data_in[lane*24 +: 24]),
                .pe_addr_valid_out(pe_weight_addr_valid_out[lane]),
                .pe_addr_ready_in(pe_weight_addr_ready_in[lane]),
                .pe_addr_out(pe_weight_addr_out[lane*7 +: 7]),
                .pe_data_valid_out(pe_weight_data_valid_out[lane]),
                .pe_data_ready_in(pe_weight_data_ready_in[lane]),
                .pe_data_out(pe_weight_data_out[lane*24 +: 24]),
                .horizontal_addr_valid_out(horizontal_weight_addr_valid_out[lane]),
                .horizontal_addr_ready_in(horizontal_weight_addr_ready_in[lane]),
                .horizontal_addr_out(horizontal_weight_addr_out[lane*7 +: 7]),
                .horizontal_data_valid_out(horizontal_weight_data_valid_out[lane]),
                .horizontal_data_ready_in(horizontal_weight_data_ready_in[lane]),
                .horizontal_data_out(horizontal_weight_data_out[lane*24 +: 24])
            );
        end

        for (lane = 0; lane < 4; lane = lane + 1) begin : g_psum_router
            Psum_Router u_psum_router (
                .data_in_sel_in(psum_data_in_sel_in[lane]),
                .route_to_pe_in(psum_route_to_pe_in[lane]),
                .pe_return_valid_in(pe_psum_return_valid_in[lane]),
                .pe_return_ready_out(pe_psum_return_ready_out[lane]),
                .pe_return_data_in(pe_psum_return_data_in[lane*42 +: 42]),
                .local_return_valid_out(local_psum_return_valid_out[lane]),
                .local_return_ready_in(local_psum_return_ready_in[lane]),
                .local_return_data_out(local_psum_return_data_out[lane*42 +: 42]),
                .local_forward_valid_in(local_psum_forward_valid_in[lane]),
                .local_forward_ready_out(local_psum_forward_ready_out[lane]),
                .local_forward_data_in(local_psum_forward_data_in[lane*42 +: 42]),
                .north_forward_valid_in(north_psum_forward_valid_in[lane]),
                .north_forward_ready_out(north_psum_forward_ready_out[lane]),
                .north_forward_data_in(north_psum_forward_data_in[lane*42 +: 42]),
                .pe_forward_valid_out(pe_psum_forward_valid_out[lane]),
                .pe_forward_ready_in(pe_psum_forward_ready_in[lane]),
                .pe_forward_data_out(pe_psum_forward_data_out[lane*42 +: 42]),
                .south_forward_valid_out(south_psum_forward_valid_out[lane]),
                .south_forward_ready_in(south_psum_forward_ready_in[lane]),
                .south_forward_data_out(south_psum_forward_data_out[lane*42 +: 42])
            );
        end
    endgenerate

endmodule
